// frontend-react/src/App.tsx
import { Layout, Menu } from 'antd'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { AppstoreOutlined, InboxOutlined, ImportOutlined } from '@ant-design/icons'

const { Header, Content } = Layout

function App() {
  const navigate = useNavigate()
  const location = useLocation()

  const menuItems = [
    { key: '/products', icon: <AppstoreOutlined />, label: '商品管理' },
    { key: '/inventory', icon: <InboxOutlined />, label: '库存查询' },
    { key: '/inbound', icon: <ImportOutlined />, label: '入库管理' },
  ]

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Header style={{ display: 'flex', alignItems: 'center', padding: '0 24px' }}>
        <h2 style={{ color: '#fff', margin: 0, marginRight: 40 }}> WMS 仓储管理系统</h2>
        <Menu
          theme="dark"
          mode="horizontal"
          selectedKeys={[location.pathname]}
          items={menuItems}
          onClick={({ key }) => navigate(key)}
          style={{ flex: 1, minWidth: 0 }}
        />
      </Header>
      <Content style={{ padding: 24, background: '#f5f5f5' }}>
        <Outlet />
      </Content>
    </Layout>
  )
}

export default App

// frontend-vue/src/App.vue
<script setup lang="ts">
</script>

<template>
  <el-container style="min-height: 100vh">
    <el-header style="background: #409eff; color: white; display: flex; align-items: center; padding: 0 20px">
      <h2 style="margin: 0"> WMS 仓储管理系统</h2>
      <el-menu
        mode="horizontal"
        :default-active="$route.path"
        router
        style="margin-left: 40px; border-bottom: none; flex: 1"
        background-color="#409eff"
        text-color="#fff"
        active-text-color="#ffd04b"
      >
        <el-menu-item index="/products">商品管理</el-menu-item>
        <el-menu-item index="/inventory">库存查询</el-menu-item>
        <el-menu-item index="/inbound">入库管理</el-menu-item>
      </el-menu>
    </el-header>

    <el-main style="padding: 20px">
      <router-view />
    </el-main>
  </el-container>
</template>

<style>
body {
  margin: 0;
  font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB', Arial, sans-serif;
}
</style>
